import * as vscode from 'vscode';
import { spawn, ChildProcess } from 'child_process';
import * as path from 'path';
import { HubConnection } from './transport';
import { CollaborationPanel } from './panel';

let hub: HubConnection | undefined; let runtime: ChildProcess | undefined; let panel: CollaborationPanel | undefined;
const tokenKey = 'atlantis.ownerToken';
export function activate(context: vscode.ExtensionContext) {
  const getHub = () => hub;
  panel = new CollaborationPanel(context.extensionUri, getHub);
  context.subscriptions.push(vscode.window.registerWebviewViewProvider('atlantis.collaboration', panel, { webviewOptions: { retainContextWhenHidden: true } }));
  const connect = vscode.commands.registerCommand('atlantis.connect', async () => { const server = await vscode.window.showInputBox({ prompt: 'URL del hub Atlantis', value: vscode.workspace.getConfiguration('atlantis').get('server', 'http://127.0.0.1:8790') }); if (!server) return; const token = await vscode.window.showInputBox({ prompt: 'Token de invitación', password: true }); if (!token) return; await saveConnection(context, server, token); });
  const start = vscode.commands.registerCommand('atlantis.startHub', () => startHub(context));
  const invite = vscode.commands.registerCommand('atlantis.invite', async () => { if (!hub) return vscode.window.showErrorMessage('Conecta Atlantis primero.'); const name = await vscode.window.showInputBox({ prompt: 'Nombre de tu compañero' }); if (!name) return; const result: any = await hub.request('POST', '/v2/invites', { name, role: 'member' }); await vscode.env.clipboard.writeText(`${hub.endpoint} · token: ${result.token}`); vscode.window.showInformationMessage('Invitación copiada. Compártela por un canal seguro.'); });
  const worker = vscode.commands.registerCommand('atlantis.startWorker', () => startWorker(context));
  const task = vscode.commands.registerCommand('atlantis.createTask', () => panel?.post({ type: 'focusTask' }));
  const open = vscode.commands.registerCommand('atlantis.open', () => vscode.commands.executeCommand('workbench.view.extension.atlantis'));
  context.subscriptions.push(connect, start, invite, worker, task, open); restore(context);
}
async function saveConnection(context: vscode.ExtensionContext, server: string, token: string) { await context.secrets.store(tokenKey, token); hub?.close(); hub = new HubConnection(server, token); hub.onEvent(event => panel?.event(event)); await hub.refresh(); hub.connect(); panel?.post({ type: 'state', state: hub.state }); vscode.window.showInformationMessage('Atlantis conectado.'); }
async function restore(context: vscode.ExtensionContext) { const token = await context.secrets.get(tokenKey); const server = vscode.workspace.getConfiguration('atlantis').get<string>('server', 'http://127.0.0.1:8790'); if (token) try { await saveConnection(context, server, token); } catch { /* panel shows disconnected state */ } }
function startHub(context: vscode.ExtensionContext) { const workspace = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath; if (!workspace) return vscode.window.showErrorMessage('Abre una carpeta para crear el espacio.'); const configured = vscode.workspace.getConfiguration('atlantis').get<string>('runtimePath', ''); const packaged = process.platform === 'win32' ? path.join(context.extensionPath, 'runtime', 'atlantis-runtime.exe') : path.join(context.extensionPath, 'runtime', 'atlantis-runtime'); const executable = configured || packaged; const configuredPython = vscode.workspace.getConfiguration('atlantis').get<string>('pythonPath', process.platform === 'win32' ? 'python' : 'python3'); const cwd = vscode.workspace.getConfiguration('atlantis').get<string>('runtimeCwd', ''); const sourceMode = !configured && !require('fs').existsSync(packaged); const command = sourceMode ? configuredPython : executable; const args = sourceMode ? ['-m', 'atlantis_runtime', '--workspace', workspace, '--port', '8790', '--name', 'Daniel'] : ['--workspace', workspace, '--port', '8790', '--name', 'Daniel']; const proc = runtime = spawn(command, args, { cwd: cwd || workspace, env: { ...process.env, PYTHONPATH: cwd ? path.join(cwd, 'nexo') : process.env.PYTHONPATH }, stdio: ['ignore', 'pipe', 'pipe'] }); proc.stdout?.setEncoding('utf8'); let buffer=''; proc.stdout?.on('data', chunk => { buffer += chunk; const lines=buffer.split(/\r?\n/); buffer=lines.pop()||''; for(const line of lines) try { const ready=JSON.parse(line); if(ready.type==='ready') void saveConnection(context, ready.server, ready.token); } catch {} }); proc.stderr?.on('data', chunk => console.error('[Atlantis runtime]', chunk.toString())); proc.on('error', error => vscode.window.showErrorMessage(`No se pudo iniciar Atlantis Runtime: ${error.message}`)); }
async function startWorker(context: vscode.ExtensionContext) { if (!hub) return vscode.window.showErrorMessage('Conecta Atlantis primero.'); const workspace = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath; if (!workspace) return vscode.window.showErrorMessage('Abre la carpeta de trabajo del worker.'); const allow = await vscode.window.showWarningMessage('Hermes podrá modificar un worktree aislado y ejecutar comandos. ¿Lo autorizas para esta sesión?', 'Autorizar', 'Cancelar'); if (allow !== 'Autorizar') return; const name = await vscode.window.showInputBox({ prompt: 'Nombre de este Hermes', value: 'Hermes-Daniel' }); if (!name) return; const invite: any = await hub.request('POST', '/v2/invites', { name, role: 'worker' }); const py = vscode.workspace.getConfiguration('atlantis').get<string>('pythonPath', process.platform === 'win32' ? 'python' : 'python3'); const cwd = vscode.workspace.getConfiguration('atlantis').get<string>('runtimeCwd', ''); const child = spawn(py, ['-m', 'atlantis_worker', '--server', hub.endpoint, '--workspace', workspace, '--token-env', 'ATLANTIS_WORKER_TOKEN', '--allow-execution'], { cwd: cwd || workspace, env: { ...process.env, PYTHONPATH: cwd ? path.join(cwd, 'nexo') : process.env.PYTHONPATH, ATLANTIS_WORKER_TOKEN: invite.token }, stdio: ['ignore', 'pipe', 'pipe'] }); child.stderr?.on('data', chunk => console.error('[Atlantis worker]', chunk.toString())); child.stdout?.on('data', chunk => console.log('[Atlantis worker]', chunk.toString())); vscode.window.showInformationMessage(`Worker ${name} conectado al hub.`); }
export function deactivate() { hub?.close(); runtime?.kill(); }
